version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env.postgres

  redis:
    image: redis:4.0-alpine

  sidekiq:
    build: .
    command: bundle exec sidekiq
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - .:/myapp
    env_file:
      - .env

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
    env_file:
      - .env